version: "3.9"
services: 
  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: events
    volumes:
      - ./postgresdb:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/1.sql
      - ./participants.sql:/docker-entrypoint-initdb.d/2.sql

    ports: 
      - 5432:5432